app:
  name: auth
db:
  adapter: postgresql
  host: localhost
  user: postgres
logger:
  path: log/app.log
  level: info
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST']%>
  user: <%= ENV['RABBITMQ_USER']%>
  password: <%= ENV['RABBITMQ_PASS']%>
